### ISSUE TITLE
Python 3.5 Support

### ISSUE THREAD

**Issue by diggetybo** [Carreau/posts#9]
With regards to 'The Sound of Hydrogen' audio player. I noticed the io module has really changed in Python 3.5, can you offer a Python 3.5 friendly version of your player? It's very impressive, I'd like to use it without having to go back to 2.7. Please advise, thank you.

**Comment by Carreau** [comment]
I'll have a look thanks !

There shoudl be an "Audio" object available now, see for example https://github.com/minrk/ligo-binder/blob/master/GW150914_tutorial.ipynb for an example on hw to use it.

**Comment by diggetybo** [comment]
After checking out the very interesting ligo-binder notebook, I noticed one drawback of the audio object. It doesn't seem to be able to ouput from within a for loop. This seems to be the behavior on different data sets as well as on 2 different machines I tried it on. So, I'm still leaning towards your .wav player, It does work within for loops, but not sure what to change to get it running in Python 3.5. Keep me posted!

**Comment by Carreau** [comment]
> After checking out the very interesting ligo-binder notebook, I noticed one drawback of the audio object. It doesn't seem to be able to ouput from within my for loop. This seems to be the behavior on different data sets as well as on 2 different machines I tried it on. However, it did succeed in doing so in the ligo-binder notebook. I'm not sure why the results vary that way. I also like having the freedom to be able to adjust the audio control's width and so forth. So, I'm still leaning towards your .wav player, It does work within my for loops as is, but not sure what to change to get it running in Python 3.5. Keep me posted!

That's likely because you need to `display` it.

```
from IPython.display import display,Audio

for thing in stuff:
    display(Audio(thing))
```

That the same thing than any other Python objects:

```
for i in range(10):
    int(i) # print nothing.
```
vs 
```
for i in range(10):
    print(int(i))
```

**Comment by Carreau** [comment]
I've push a Python 3 notebook,  it should take a few minutes for the site to be rebuilt.

**Comment by diggetybo** [comment]
Ok that's excellent, thank you!! I'm looking forward to using it, an inline .wav player is such a great idea.
